Lunchbox: lunchbox::Condition Class Reference
lunchbox::Condition Class Reference
A condition variable and associated lock.
#include <condition.h>
Public Member Functions
Condition ()
Construct a new condition variable.
~Condition ()
Destruct this condition variable.
void lock ()
Lock the mutex.
void unlock ()
Unlock the mutex.
void signal ()
Signal the condition.
void broadcast ()
Broadcast the condition.
void wait ()
Atomically unlock the mutex, wait for a signal and relock the mutex.
bool timedWait (const uint32_t timeout)
Atomically unlock the mutex, wait for a signal and relock the mutex.
Detailed Description
A condition variable and associated lock.
Follows closely pthread_condition and mutex
Definition at line 33 of file condition.h.
Constructor & Destructor Documentation
lunchbox::Condition::Condition ()
Construct a new condition variable.
Version:
1.0
lunchbox::Condition::~Condition ()
Destruct this condition variable.
Version:
1.0
Member Function Documentation
void lunchbox::Condition::broadcast ()
Broadcast the condition.
Version:
1.0
Referenced by lunchbox::Monitor< T >::operator++(), lunchbox::Monitor< T >::operator--(), lunchbox::Monitor< T >::operator|=(), and lunchbox::Monitor< T >::set().
void lunchbox::Condition::lock ()
Lock the mutex.
Version:
1.0
Referenced by lunchbox::MTQueue< T, S >::clear(), lunchbox::MTQueue< T, S >::getBack(), lunchbox::MTQueue< T, S >::getFront(), lunchbox::Monitor< T >::operator++(), lunchbox::Monitor< T >::operator--(), lunchbox::MTQueue< T, S >::operator=(), lunchbox::MTQueue< T, S >::operator[](), lunchbox::Monitor< T >::operator|=(), lunchbox::MTQueue< T, S >::pop(), lunchbox::MTQueue< T, S >::push(), lunchbox::MTQueue< T, S >::pushFront(), lunchbox::Monitor< T >::set(), lunchbox::MTQueue< T, S >::setMaxSize(), lunchbox::MTQueue< T, S >::timedPop(), lunchbox::Monitor< T >::timedWaitEQ(), lunchbox::Monitor< T >::timedWaitGE(), lunchbox::Monitor< T >::timedWaitNE(), lunchbox::MTQueue< T, S >::tryPop(), lunchbox::Monitor< T >::waitEQ(), lunchbox::Monitor< T >::waitGE(), lunchbox::Monitor< T >::waitLE(), lunchbox::Monitor< T >::waitNE(), and lunchbox::MTQueue< T, S >::waitSize().
void lunchbox::Condition::signal ()
Signal the condition.
Version:
1.0
Referenced by lunchbox::MTQueue< T, S >::clear(), lunchbox::MTQueue< T, S >::operator=(), lunchbox::MTQueue< T, S >::pop(), lunchbox::MTQueue< T, S >::push(), lunchbox::MTQueue< T, S >::pushFront(), lunchbox::MTQueue< T, S >::setMaxSize(), lunchbox::MTQueue< T, S >::timedPop(), and lunchbox::MTQueue< T, S >::tryPop().
bool lunchbox::Condition::timedWait (const uint32_t timeout)
Atomically unlock the mutex, wait for a signal and relock the mutex.
The operation is aborted after the given timeout and false is returned.
Parameters:
timeout the timeout in milliseconds to wait for the signal.
Returns:
true on success, false on timeout.
Version:
1.0
Referenced by lunchbox::MTQueue< T, S >::timedPop(), lunchbox::Monitor< T >::timedWaitEQ(), lunchbox::Monitor< T >::timedWaitGE(), and lunchbox::Monitor< T >::timedWaitNE().
void lunchbox::Condition::unlock ()
Unlock the mutex.
Version:
1.0
Referenced by lunchbox::MTQueue< T, S >::clear(), lunchbox::MTQueue< T, S >::getBack(), lunchbox::MTQueue< T, S >::getFront(), lunchbox::Monitor< T >::operator++(), lunchbox::Monitor< T >::operator--(), lunchbox::MTQueue< T, S >::operator=(), lunchbox::MTQueue< T, S >::operator[](), lunchbox::Monitor< T >::operator|=(), lunchbox::MTQueue< T, S >::pop(), lunchbox::MTQueue< T, S >::push(), lunchbox::MTQueue< T, S >::pushFront(), lunchbox::Monitor< T >::set(), lunchbox::MTQueue< T, S >::setMaxSize(), lunchbox::MTQueue< T, S >::timedPop(), lunchbox::Monitor< T >::timedWaitEQ(), lunchbox::Monitor< T >::timedWaitGE(), lunchbox::Monitor< T >::timedWaitNE(), lunchbox::MTQueue< T, S >::tryPop(), lunchbox::Monitor< T >::waitEQ(), lunchbox::Monitor< T >::waitGE(), lunchbox::Monitor< T >::waitLE(), lunchbox::Monitor< T >::waitNE(), and lunchbox::MTQueue< T, S >::waitSize().
void lunchbox::Condition::wait ()
Atomically unlock the mutex, wait for a signal and relock the mutex.
Version:
1.0
Referenced by lunchbox::MTQueue< T, S >::operator[](), lunchbox::MTQueue< T, S >::pop(), lunchbox::MTQueue< T, S >::push(), lunchbox::MTQueue< T, S >::pushFront(), lunchbox::MTQueue< T, S >::setMaxSize(), lunchbox::Monitor< T >::waitEQ(), lunchbox::Monitor< T >::waitGE(), lunchbox::Monitor< T >::waitLE(), lunchbox::Monitor< T >::waitNE(), and lunchbox::MTQueue< T, S >::waitSize().
The documentation for this class was generated from the following file:
condition.h