Lunchbox: lunchbox Namespace Reference
lunchbox Namespace Reference
Abstraction layer and common utilities for multi-threaded programming.
Classes
class Atomic
A variable with atomic semantics and standalone atomic operations.
class Buffer
A simple memory buffer with some helper functions.
class Clock
A class for time measurements.
class Condition
A condition variable and associated lock.
class DSO
Helper to access dynamic shared objects (DSO)
class PtrHash
A hash for pointer keys.
struct hashRefPtr
A hash function for RefPtr keys.
class RefPtrHash
A hash for RefPtr keys.
class UUIDHash
A hash for UUID keys.
class IndexIterator
Counter-based, as opposed to pointer-based, iterator for any container.
class Launcher
The launcher executes a command from a separate process.
class LFQueue
A thread-safe, lock-free queue with non-blocking access.
class LFVector
STL-like vector implementation providing certain thread-safety guarantees.
class LFVectorIterator
class Lock
A lock (mutex) primitive.
class Lockable
A convenience structure to hold data together with a lock for access.
class LogBuffer
class Log
The logging class.
class MemoryMap
Helper to map a file to a memory address (mmap)
class Monitor
A monitor primitive.
class MTQueue
A thread-safe queue with a blocking read access.
class NonCopyable
Base class to make objects non-copyable.
class OMP
Base class for OpenMP functionality.
class PerThread
Implements thread-specific storage for C++ objects.
class PerThreadRef
Thread-specific storage for a RefPtr.
class Pool
An object allocation pool.
class Referenced
Base class for referenced objects.
class RefPtr
A smart reference pointer, aka boost::intrusive_ptr.
class RequestHandler
A thread-safe request handler.
class RNG
A random number generator.
class ScopedMutex
A scoped mutex.
class Servus
Simple wrapper for ZeroConf key/value pairs.
class SpinLock
A fast lock for uncontended memory access.
class Thread
An utility class to execute code in a separate execution thread.
class ThreadID
An utility class to wrap OS-specific thread identifiers.
class TimedLock
A mutex with timeout capabilities.
class uint128_t
A base type for 128 bit unsigned integer values.
class UUID
Provides a universally unique identifier.
class Version
Information about the current LunchBox version.
Functions
void memoryBarrier ()
Perform a full memory barrier.
template<class T >
int32_t getIndexOfLastBit (T value)
template<>
int32_t getIndexOfLastBit< uint32_t > (uint32_t value)
template<>
int32_t getIndexOfLastBit< uint64_t > (uint64_t value)
void abort ()
void checkHeap ()
std::ostream & sysError (std::ostream &os)
Print a textual description of the current system error.
std::ostream & backtrace (std::ostream &os)
Print the current call stack.
std::string demangleTypeID (const char *mangled)
template<class T >
std::string className (T *object)
Print the RTTI name of the given class.
Strings searchDirectory (const std::string &directory, const std::string &pattern)
Retrieve a list of files in a directory matching a pattern.
std::string getFilename (const std::string &filename)
std::string getDirname (const std::string &filename)
bool init (const int argc, char **argv)
Initialize the Lunchbox base classes.
bool exit ()
De-initialize the Lunchbox base classes.
template<class T >
std::ostream & operator<< (std::ostream &os, const LFVector< T > &v)
Output the vector and up to 256 items to the ostream.
template<class D , class L >
std::ostream & operator<< (std::ostream &os, const Lockable< D, L > &l)
Print the data to the given output stream.
std::ostream & indent (std::ostream &os)
Increases the indentation level of the Log stream, causing subsequent lines to be intended by four characters.
std::ostream & exdent (std::ostream &os)
Decrease the indent of the Log stream.
std::ostream & disableFlush (std::ostream &os)
Disable flushing of the Log stream.
std::ostream & enableFlush (std::ostream &os)
Re-enable flushing of the Log stream.
std::ostream & forceFlush (std::ostream &os)
Flush the Log stream regardless of the auto-flush state.
std::ostream & disableHeader (std::ostream &os)
Disable printing of the Log header for subsequent lines.
std::ostream & enableHeader (std::ostream &os)
Re-enable printing of the Log header.
template<typename T >
std::ostream & operator<< (std::ostream &os, const Monitor< T > &monitor)
Print the monitor to the given output stream.
template<class T >
void perThreadDelete (T *object)
Default PerThread destructor deleting the object.
template<class T >
void perThreadNoDelete (T *object)
Empty PerThread destructor.
template<class T >
std::ostream & operator<< (std::ostream &os, const RefPtr< T > &rp)
Print the reference pointer to the given output stream.
template<class T >
std::string className (const RefPtr< T > &rp)
std::ostream & operator<< (std::ostream &, const RequestHandler &)
void sleep (const uint32_t milliSeconds)
Sleep the current thread for a number of milliseconds.
std::ostream & operator<< (std::ostream &, const ThreadID &)
Print the thread to the given output stream.
std::ostream & operator<< (std::ostream &os, const uint128_t &id)
ostream operator for 128 bit unsigned integers.
uint128_t operator+ (const uint128_t &a, const uint64_t &b)
Add a 64 bit value to a 128 bit value.
uint128_t operator- (const uint128_t &a, const uint64_t &b)
Subtract a 64 bit value from a 128 bit value.
uint128_t operator& (const uint128_t &a, const uint128_t &b)
Bitwise and operation on two 128 bit values.
uint128_t operator| (const uint128_t &a, const uint128_t &b)
Bitwise or operation on two 128 bit values.
uint128_t make_uint128 (const char *string)
Create a 128 bit integer based on a string.
Typedefs
typedef Monitor< bool > Monitorb
A boolean monitor variable.
typedef Monitor< uint32_t > Monitoru
An unsigned 32bit integer monitor.
typedef ScopedMutex< SpinLock,
ReadOp > ScopedFastRead
A scoped mutex for a fast uncontended read operation.
typedef ScopedMutex< SpinLock,
WriteOp > ScopedFastWrite
A scoped mutex for a fast uncontended write operation.
typedef ScopedMutex< Lock, ReadOp > ScopedRead
A scoped mutex for a read operation.
typedef ScopedMutex< Lock,
WriteOp > ScopedWrite
A scoped mutex for a write operation.
typedef std::vector< std::string > Strings
A vector of std::strings.
typedef Strings::const_iterator StringsCIter
typedef Atomic< int32_t > a_int32_t
An atomic 32 bit integer variable.
typedef Atomic< ssize_t > a_ssize_t
An atomic signed size variable.
typedef Buffer< uint8_t > Bufferb
a byte buffer
Enumerations
enum LogLevel {
LOG_ERROR = 1, LOG_WARN, LOG_INFO, LOG_VERB,
LOG_ALL
}
The logging levels.
enum LogTopic { LOG_CUSTOM = 0x10, LOG_ANY = 0xffffu }
The logging topics.
Detailed Description
Abstraction layer and common utilities for multi-threaded programming.
Lunchbox provides C++ classes to abstract the underlying operating system and to implement common utilities for multi-threaded C++ programs. Classes with non-virtual destructors are not intended to be subclassed.
Function Documentation
std::ostream& lunchbox::backtrace (std::ostream & os)
Print the current call stack.
May not be implemented on all platforms.
Version:
1.0
Referenced by lunchbox::Referenced::ref().
template<class T > std::string lunchbox::className (T * object) [inline]
Print the RTTI name of the given class.
Version:
1.0
Definition at line 62 of file debug.h.
Referenced by lunchbox::PerThread< T, D >::operator*(), lunchbox::RefPtr< T >::operator*(), lunchbox::RefPtr< T >::operator->(), and operator<<().
std::ostream& lunchbox::disableFlush (std::ostream & os)
Disable flushing of the Log stream.
Version:
1.0
Referenced by operator<<().
std::ostream& lunchbox::disableHeader (std::ostream & os)
Disable printing of the Log header for subsequent lines.
Version:
1.0
std::ostream& lunchbox::enableFlush (std::ostream & os)
Re-enable flushing of the Log stream.
Version:
1.0
Referenced by operator<<().
std::ostream& lunchbox::enableHeader (std::ostream & os)
Re-enable printing of the Log header.
Version:
1.0
std::ostream& lunchbox::exdent (std::ostream & os)
Decrease the indent of the Log stream.
Version:
1.0
bool lunchbox::exit ()
De-initialize the Lunchbox base classes.
Returns:
true if the library was successfully de-initialised, false otherwise.
Version:
1.0
std::ostream& lunchbox::forceFlush (std::ostream & os)
Flush the Log stream regardless of the auto-flush state.
Version:
1.0
std::string lunchbox::getDirname (const std::string & filename)
Returns:
the directory name part of a path.
Version:
1.0
std::string lunchbox::getFilename (const std::string & filename)
Returns:
the file name part of a path.
Version:
1.0
template<class T > int32_t lunchbox::getIndexOfLastBit (T value)
Returns:
the position of the last (most significant) set bit, or -1.
Referenced by lunchbox::LFVector< T, nSlots >::LFVector(), and lunchbox::LFVector< T, nSlots >::operator[]().
std::ostream& lunchbox::indent (std::ostream & os)
Increases the indentation level of the Log stream, causing subsequent lines to be intended by four characters.
Version:
1.0
bool lunchbox::init (const int argc, char ** argv)
Initialize the Lunchbox base classes.
Parameters:
argc the command line argument count.
argv the command line argument values.
Returns:
true if the library was successfully initialised, false otherwise
Version:
1.0
uint128_t lunchbox::make_uint128 (const char * string)
Create a 128 bit integer based on a string.
The MD5 hash of the given text is used to form the uint128_t.
Parameters:
string the string to form the uint128_t from.
Version:
1.3.2
void lunchbox::memoryBarrier () [inline]
Perform a full memory barrier.
Definition at line 35 of file atomic.h.
Referenced by lunchbox::Atomic< T >::operator!=(), lunchbox::Atomic< T >::operator=(), and lunchbox::Atomic< T >::operator==().
uint128_t lunchbox::operator& (const uint128_t & a, const uint128_t & b) [inline]
Bitwise and operation on two 128 bit values.
Version:
1.1.5
Definition at line 245 of file uint128_t.h.
References lunchbox::uint128_t::high(), and lunchbox::uint128_t::low().
uint128_t lunchbox::operator+ (const uint128_t & a, const uint64_t & b) [inline]
Add a 64 bit value to a 128 bit value.
Version:
1.0
Definition at line 225 of file uint128_t.h.
References lunchbox::uint128_t::high(), and lunchbox::uint128_t::low().
uint128_t lunchbox::operator- (const uint128_t & a, const uint64_t & b) [inline]
Subtract a 64 bit value from a 128 bit value.
Version:
1.0
Definition at line 235 of file uint128_t.h.
References lunchbox::uint128_t::high(), and lunchbox::uint128_t::low().
std::ostream & lunchbox::operator<< (std::ostream & os, const uint128_t & id) [inline]
ostream operator for 128 bit unsigned integers.
Version:
1.0
Definition at line 215 of file uint128_t.h.
std::ostream& lunchbox::operator<< (std::ostream & , const ThreadID &)
Print the thread to the given output stream.
template<class D , class L > std::ostream& lunchbox::operator<< (std::ostream & os, const Lockable< D, L > & l) [inline]
Print the data to the given output stream.
Definition at line 68 of file lockable.h.
References disableFlush(), and enableFlush().
template<class T > std::ostream& lunchbox::operator<< (std::ostream & os, const RefPtr< T > & rp) [inline]
Print the reference pointer to the given output stream.
Definition at line 178 of file refPtr.h.
References disableFlush(), and enableFlush().
template<typename T > std::ostream& lunchbox::operator<< (std::ostream & os, const Monitor< T > & monitor) [inline]
Print the monitor to the given output stream.
Version:
1.0
Definition at line 338 of file monitor.h.
References lunchbox::Monitor< T >::get().
template<class T > std::ostream& lunchbox::operator<< (std::ostream & os, const LFVector< T > & v) [inline]
Output the vector and up to 256 items to the ostream.
Version:
0.1
Definition at line 448 of file lfVector.h.
References className().
uint128_t lunchbox::operator| (const uint128_t & a, const uint128_t & b) [inline]
Bitwise or operation on two 128 bit values.
Version:
1.1.5
Definition at line 254 of file uint128_t.h.
References lunchbox::uint128_t::high(), and lunchbox::uint128_t::low().
template<class T > void lunchbox::perThreadDelete (T * object)
Default PerThread destructor deleting the object.
Version:
1.1.2
Definition at line 31 of file perThread.h.
template<class T > void lunchbox::perThreadNoDelete (T * object)
Empty PerThread destructor.
Version:
1.1.2
Definition at line 34 of file perThread.h.
Strings lunchbox::searchDirectory (const std::string & directory, const std::string & pattern)
Retrieve a list of files in a directory matching a pattern.
Only foo*bar pattern are implemented currently.
Returns:
all file names matching the given pattern in the given directory.
Version:
1.0
void lunchbox::sleep (const uint32_t milliSeconds)
Sleep the current thread for a number of milliseconds.
Version:
1.0
std::ostream& lunchbox::sysError (std::ostream & os)
Print a textual description of the current system error.
The current system error is OS-specific, e.g., errno or GetLastError().
Version:
1.0
Typedef Documentation
typedef ScopedMutex< SpinLock, ReadOp > lunchbox::ScopedFastRead
A scoped mutex for a fast uncontended read operation.
Version:
1.1.2
Definition at line 93 of file scopedMutex.h.
typedef ScopedMutex< SpinLock, WriteOp > lunchbox::ScopedFastWrite
A scoped mutex for a fast uncontended write operation.
Version:
1.1.2
Definition at line 96 of file scopedMutex.h.
typedef ScopedMutex< Lock, ReadOp > lunchbox::ScopedRead
A scoped mutex for a read operation.
Version:
1.1.5
Definition at line 99 of file scopedMutex.h.
typedef ScopedMutex< Lock, WriteOp > lunchbox::ScopedWrite
A scoped mutex for a write operation.
Version:
1.1.5
Definition at line 102 of file scopedMutex.h.
typedef std::vector< std::string > lunchbox::Strings
A vector of std::strings.
Version:
1.0
Definition at line 129 of file types.h.
Enumeration Type Documentation
enum lunchbox::LogLevel
The logging levels.
Version:
1.0
Enumerator:
LOG_ERROR
Output critical errors.
LOG_WARN
Output potentially critical warnings.
LOG_INFO
Output informational messages.
LOG_VERB
Be noisy.
Definition at line 40 of file log.h.
enum lunchbox::LogTopic
The logging topics.
See also:
net/log.h, client/log.h
Version:
1.0
Enumerator:
LOG_CUSTOM
Log topics for other namespaces start here.
LOG_ANY
Log all Lunchbox topics.
Definition at line 55 of file log.h.