Lunchbox: stdExt.h File Reference
stdExt.h File Reference
Include extensions to the STL and define a uniform interface to them.
#include <lunchbox/compiler.h>
#include <lunchbox/uint128_t.h>
#include <algorithm>
#include <string>
#include <vector>
#include <hash_map>
#include <hash_set>
Classes
struct hash< lunchbox::uint128_t >
std::string hash function.
Defines
#define LB_STDEXT_STD
#define LB_STDEXT_NAMESPACE_OPEN namespace std {
#define LB_STDEXT_NAMESPACE_CLOSE }
Functions
template<typename C >
void usort (C &c)
MSVC.
template<typename T >
std::vector< T >::iterator find (std::vector< T > &container, const T &element)
Find the element in the given vector.
template<typename T >
std::vector< T >::const_iterator find (const std::vector< T > &container, const T &element)
Find the element in the given vector.
template<typename T , typename P >
std::vector< T >::iterator find_if (std::vector< T > &container, const P &predicate)
Find the element matching the predicate.
template<typename T , typename P >
std::vector< T >::const_iterator find_if (std::vector< const T > &container, const P &predicate)
Find the element matching the predicate.
Detailed Description
Include extensions to the STL and define a uniform interface to them.
Definition in file stdExt.h.
Function Documentation
template<typename T > std::vector< T >::iterator find (std::vector< T > & container, const T & element)
Find the element in the given vector.
Version:
1.0
Definition at line 196 of file stdExt.h.
Referenced by find().
template<typename T > std::vector< T >::const_iterator find (const std::vector< T > & container, const T & element)
Find the element in the given vector.
Version:
1.0
Definition at line 201 of file stdExt.h.
References find().
template<typename T , typename P > std::vector< T >::iterator find_if (std::vector< T > & container, const P & predicate)
Find the element matching the predicate.
Version:
1.0
Definition at line 206 of file stdExt.h.
Referenced by find_if().
template<typename T , typename P > std::vector<T>::const_iterator find_if (std::vector< const T > & container, const P & predicate)
Find the element matching the predicate.
Version:
1.0
Definition at line 211 of file stdExt.h.
References find_if().
template<typename C > void usort (C & c)
MSVC.
Uniquely sorts and eliminates duplicates in a STL container.
Version:
1.0
Definition at line 188 of file stdExt.h.