Collage: eq::net::DataIStream Class Reference
eq::net::DataIStream Class Reference
A std::istream-like input data stream for binary data.
#include <dataIStream.h>
Public Member Functions
Internal
DataIStream ()
DataIStream (const DataIStream &)
virtual ~DataIStream ()
virtual size_t nRemainingBuffers () const =0
Get the number of remaining buffers.
virtual uint128_t getVersion () const =0
virtual void reset ()
Data input
template<typename T >
DataIStream & operator>> (T &value)
Read a plain data item.
template<typename T >
DataIStream & operator>> (std::vector< T > &value)
Read a std::vector of serializable items.
template<typename O , typename C >
void deserializeChildren (O *object, const std::vector< C * > &old, std::vector< C * > &result)
Deserialize child objects.
void read (void *data, uint64_t size)
Read a number of bytes from the stream into a buffer.
const void * getRemainingBuffer ()
Get the pointer to the remaining data in the current buffer.
uint64_t getRemainingBufferSize ()
Get the size of the remaining data in the current buffer.
void advanceBuffer (const uint64_t offset)
Advance the current buffer by a number of bytes.
Specialized input operators
template<>
DataIStream & operator>> (std::string &str)
Read a std::string.
template<>
DataIStream & operator>> (Object *&object)
Deserialize an object (id+version).
template<>
DataIStream & operator>> (std::vector< uint8_t > &value)
Optimized specialization to read a std::vector of uint8_t.
template<>
DataIStream & operator>> (std::vector< uint32_t > &value)
Optimized specialization to read a std::vector of uint32_t.
template<>
DataIStream & operator>> (std::vector< int32_t > &value)
Optimized specialization to read a std::vector of int32_t.
template<>
DataIStream & operator>> (std::vector< uint64_t > &value)
Optimized specialization to read a std::vector of uint64_t.
template<>
DataIStream & operator>> (std::vector< int64_t > &value)
Optimized specialization to read a std::vector of int64_t.
template<>
DataIStream & operator>> (std::vector< float > &value)
Optimized specialization to read a std::vector of float.
template<>
DataIStream & operator>> (std::vector< double > &value)
Optimized specialization to read a std::vector of double.
template<>
DataIStream & operator>> (std::vector< ObjectVersion > &value)
Optimized specialization to read a std::vector of ObjectVersion.
Protected Member Functions
virtual bool getNextBuffer (uint32_t *compressor, uint32_t *nChunks, const void **chunkData, uint64_t *size)=0
Detailed Description
A std::istream-like input data stream for binary data.
Definition at line 35 of file dataIStream.h.
Member Function Documentation
void eq::net::DataIStream::advanceBuffer (const uint64_t offset)
Advance the current buffer by a number of bytes.
Referenced by operator>>().
template<typename O , typename C > void eq::net::DataIStream::deserializeChildren (O * object, const std::vector< C * > & old, std::vector< C * > & result)
Deserialize child objects.
Existing children are synced to the new version. New children are created by calling the void create(C** child) method on the object, and registered or mapped to the object's session. Removed children are released by calling the void release(C*) method on the object. The resulting child vector is created in result. The old and result vector can be the same object, the result vector is cleared and rebuild completely.
const void* eq::net::DataIStream::getRemainingBuffer ()
Get the pointer to the remaining data in the current buffer.
The data written by the DataOStream on the other end is bucketized, that is, it is sent in multiple blocks. The remaining buffer and its size points into one of the buffers, that is, not all the data sent is returned by this function. However, a write operation on the other end is never segmented, that is, if the application writes n bytes to the DataOStream, a symmetric read from the DataIStream has at least n bytes available.
Referenced by operator>>().
uint64_t eq::net::DataIStream::getRemainingBufferSize ()
Get the size of the remaining data in the current buffer.
Referenced by operator>>().
virtual size_t eq::net::DataIStream::nRemainingBuffers () const [pure virtual]
Get the number of remaining buffers.
template<> DataIStream& eq::net::DataIStream::operator>> (std::vector< uint32_t > & value) [inline]
Optimized specialization to read a std::vector of uint32_t.
Definition at line 275 of file dataIStream.h.
template<> DataIStream& eq::net::DataIStream::operator>> (std::vector< int32_t > & value) [inline]
Optimized specialization to read a std::vector of int32_t.
Definition at line 280 of file dataIStream.h.
template<> DataIStream& eq::net::DataIStream::operator>> (Object *& object) [inline]
Deserialize an object (id+version).
Definition at line 179 of file dataIStream.h.
References eq::net::Object::getID().
template<> DataIStream& eq::net::DataIStream::operator>> (std::vector< int64_t > & value) [inline]
Optimized specialization to read a std::vector of int64_t.
Definition at line 290 of file dataIStream.h.
template<> DataIStream& eq::net::DataIStream::operator>> (std::vector< ObjectVersion > & value) [inline]
Optimized specialization to read a std::vector of ObjectVersion.
Definition at line 305 of file dataIStream.h.
template<typename T > DataIStream& eq::net::DataIStream::operator>> (std::vector< T > & value) [inline]
Read a std::vector of serializable items.
Definition at line 61 of file dataIStream.h.
References read().
template<typename T > DataIStream& eq::net::DataIStream::operator>> (T & value) [inline]
Read a plain data item.
Definition at line 56 of file dataIStream.h.
References read().
template<> DataIStream& eq::net::DataIStream::operator>> (std::vector< float > & value) [inline]
Optimized specialization to read a std::vector of float.
Definition at line 295 of file dataIStream.h.
template<> DataIStream& eq::net::DataIStream::operator>> (std::vector< uint8_t > & value) [inline]
Optimized specialization to read a std::vector of uint8_t.
Definition at line 270 of file dataIStream.h.
template<> DataIStream& eq::net::DataIStream::operator>> (std::string & str) [inline]
Read a std::string.
Definition at line 161 of file dataIStream.h.
References advanceBuffer(), getRemainingBuffer(), getRemainingBufferSize(), and read().
template<> DataIStream& eq::net::DataIStream::operator>> (std::vector< double > & value) [inline]
Optimized specialization to read a std::vector of double.
Definition at line 300 of file dataIStream.h.
template<> DataIStream& eq::net::DataIStream::operator>> (std::vector< uint64_t > & value) [inline]
Optimized specialization to read a std::vector of uint64_t.
Definition at line 285 of file dataIStream.h.
void eq::net::DataIStream::read (void * data, uint64_t size)
Read a number of bytes from the stream into a buffer.
Referenced by operator>>().
The documentation for this class was generated from the following file:
dataIStream.h