Collage: co::base::UUID Class Reference
co::base::UUID Class Reference
Provides a universally unique identifier.
#include <uuid.h>
Public Member Functions
UUID (const bool generate=false)
Construct a new universally unique identifier.
UUID (const uint64_t high_, const uint64_t low_)
Construct a new universally unique identifier.
UUID (const uint128_t &from)
Construct a new universally unique identifier from an unsigned 128 bit integer value.
UUID & operator= (const std::string &from)
Assign another UUID from a string representation.
bool isGenerated () const
Static Public Attributes
static COBASE_API const UUID ZERO
The NULL UUID.
Friends
struct stde::hash< co::base::UUID >
Detailed Description
Provides a universally unique identifier.
Not to be subclassed.
Definition at line 34 of file uuid.h.
Constructor & Destructor Documentation
co::base::UUID::UUID (const bool generate = false) [inline, explicit]
Construct a new universally unique identifier.
If generate is set to true, a new UUID is allocated. Otherwise the UUID is cleared, i.e., it is equal to UUID::ZERO.
Version:
1.0
Definition at line 44 of file uuid.h.
References co::base::RNG::get(), co::base::uint128_t::high(), and co::base::uint128_t::low().
co::base::UUID::UUID (const uint64_t high_, const uint64_t low_) [inline]
Construct a new universally unique identifier.
Version:
1.0
Definition at line 58 of file uuid.h.
co::base::UUID::UUID (const uint128_t & from) [inline]
Construct a new universally unique identifier from an unsigned 128 bit integer value.
Version:
1.0
Definition at line 66 of file uuid.h.
Member Function Documentation
bool co::base::UUID::isGenerated () const [inline]
Returns:
true if the UUID was generated.
Definition at line 90 of file uuid.h.
References co::base::uint128_t::high().
UUID& co::base::UUID::operator= (const std::string & from) [inline]
Assign another UUID from a string representation.
Version:
1.0
Definition at line 69 of file uuid.h.
References co::base::uint128_t::high(), and co::base::uint128_t::low().
Member Data Documentation
COBASE_API const UUID co::base::UUID::ZERO [static]
The NULL UUID.
Version:
1.0
Definition at line 93 of file uuid.h.
The documentation for this class was generated from the following file:
uuid.h