Collage: co::base::RNG Class Reference
co::base::RNG Class Reference
A random number generator.
#include <rng.h>
Public Member Functions
RNG ()
Construct a new random number generator.
~RNG ()
Destruct the random number generator.
void reseed ()
Re-initialize the seed value for pseudo RNG's.
template<typename T >
T get ()
Generate a random number.
Friends
COBASE_API bool init (const int argc, char **argv)
Initialize the Equalizer base classes.
COBASE_API bool exit ()
De-initialize the Equalizer base classes.
Detailed Description
A random number generator.
Generates a set of random, or if not supported by the operating system, pseudo-random numbers. Each instance creates its own series of numbers.
Definition at line 39 of file rng.h.
Constructor & Destructor Documentation
co::base::RNG::RNG () [inline]
Construct a new random number generator.
Version:
1.0
Definition at line 43 of file rng.h.
References reseed().
co::base::RNG::~RNG () [inline]
Destruct the random number generator.
Version:
1.0
Definition at line 46 of file rng.h.
Member Function Documentation
bool co::base::RNG::get () [inline]
Generate a random number.
The returned number is between min..max for integer types, and between 0..1 for floating-point types.
Returns:
a random number.
Version:
1.0
Definition at line 70 of file rng.h.
References EQERROR, and co::base::sysError().
Referenced by co::base::UUID::UUID().
void co::base::RNG::reseed () [inline]
Re-initialize the seed value for pseudo RNG's.
Version:
1.0
Definition at line 49 of file rng.h.
Referenced by RNG().
Friends And Related Function Documentation
COBASE_API bool exit () [friend]
De-initialize the Equalizer base classes.
Returns:
true if the library was successfully de-initialised, false otherwise.
Version:
1.0
De-initialize the Equalizer base classes.
Returns:
true if the library was successfully de-initialised, false otherwise.
COBASE_API bool init (const int argc, char ** argv) [friend]
Initialize the Equalizer base classes.
If the command line parameter '--eq-logfile <filename>' is present, all log output is redirected to the given file.
Parameters:
argc the command line argument count.
argv the command line argument values.
Returns:
true if the library was successfully initialised, false otherwise
Version:
1.0
Initialize the Equalizer base classes.
Parameters:
argc the command line argument count.
argv the command line argument values.
Returns:
true if the library was successfully initialised, false otherwise.
The documentation for this class was generated from the following file:
rng.h