Collage: eq::net::DataOStream Class Reference
eq::net::DataOStream Class Reference
A std::ostream buffering and/or retaining data in a binary format.
#include <dataOStream.h>
Public Member Functions
Internal
DataOStream ()
virtual ~DataOStream ()
void enable (const Nodes &receivers)
Enable output, locks the connections to the receivers.
void enable (NodePtr node, const bool useMulticast)
void enable ()
void disable ()
Disable, flush and unlock the output to the current receivers.
void enableSave ()
Enable copying of all data into a saved buffer.
void disableSave ()
Disable copying of all data into a saved buffer.
bool hasSentData () const
void resend (NodePtr node, const bool useMulticast)
Resend the saved buffer to the given node.
void resend (const Nodes &receivers)
Resend the saved buffer to all given nodes.
const base::Bufferb & getSaveBuffer () const
Data output
template<typename T >
DataOStream & operator<< (const T &value)
Write a plain data item by copying it to the stream.
template<typename T >
DataOStream & operator<< (const std::vector< T > &value)
Write a std::vector of serializable items.
void write (const void *data, uint64_t size)
Write a number of bytes from data into the stream.
template<typename C >
void serializeChildren (const std::vector< C * > &children)
Serialize child objects.
Specialized output operators
template<>
DataOStream & operator<< (const std::string &str)
Write a std::string.
template<>
DataOStream & operator<< (const Object *const &object)
Write an object identifier and version.
template<>
DataOStream & operator<< (const std::vector< uint8_t > &value)
Optimized specialization to write a std::vector of uint8_t.
template<>
DataOStream & operator<< (const std::vector< uint32_t > &value)
Optimized specialization to write a std::vector of uint32_t.
template<>
DataOStream & operator<< (const std::vector< int32_t > &value)
Optimized specialization to write a std::vector of int32_t.
template<>
DataOStream & operator<< (const std::vector< uint64_t > &value)
Optimized specialization to write a std::vector of uint64_t.
template<>
DataOStream & operator<< (const std::vector< int64_t > &value)
Optimized specialization to write a std::vector of int64_t.
template<>
DataOStream & operator<< (const std::vector< float > &value)
Optimized specialization to write a std::vector of float.
template<>
DataOStream & operator<< (const std::vector< double > &value)
Optimized specialization to write a std::vector of double.
template<>
DataOStream & operator<< (const std::vector< ObjectVersion > &value)
Optimized specialization to write a std::vector of ObjectVersion.
Protected Member Functions
void _flush ()
Flush remaining data in the buffer.
virtual void reset ()
Reset the whole stream.
Packet sending, implemented by the subclasses
virtual void sendData (const uint32_t compressor, const uint32_t nChunks, const void *const *chunks, const uint64_t *chunkSizes, const uint64_t size)=0
Send a data buffer (packet) to the receivers.
virtual void sendFooter (const uint32_t compressor, const uint32_t nChunks, const void *const *chunks, const uint64_t *chunkSizes, const uint64_t size)=0
Send the trailing data (packet) to the receivers.
Protected Attributes
Connections _connections
Locked connections to the receivers, if _enabled.
Friends
class DataStreamTest::Sender
Detailed Description
A std::ostream buffering and/or retaining data in a binary format.
Derived classes send the data using the appropriate command packets.
Definition at line 44 of file dataOStream.h.
Member Function Documentation
void eq::net::DataOStream::_flush () [protected]
Flush remaining data in the buffer.
void eq::net::DataOStream::disable ()
Disable, flush and unlock the output to the current receivers.
void eq::net::DataOStream::disableSave ()
Disable copying of all data into a saved buffer.
void eq::net::DataOStream::enableSave ()
Enable copying of all data into a saved buffer.
const base::Bufferb& eq::net::DataOStream::getSaveBuffer () const [inline]
Returns:
the buffer with the saved data.
Definition at line 76 of file dataOStream.h.
bool eq::net::DataOStream::hasSentData () const [inline]
Returns:
if data was sent since the last enable()
Definition at line 67 of file dataOStream.h.
template<> DataOStream& eq::net::DataOStream::operator<< (const Object *const & object) [inline]
Write an object identifier and version.
Definition at line 229 of file dataOStream.h.
References eq::net::Object::isAttached().
template<> DataOStream& eq::net::DataOStream::operator<< (const std::vector< uint32_t > & value) [inline]
Optimized specialization to write a std::vector of uint32_t.
Definition at line 272 of file dataOStream.h.
template<> DataOStream& eq::net::DataOStream::operator<< (const std::string & str) [inline]
Write a std::string.
Definition at line 217 of file dataOStream.h.
References write().
template<> DataOStream& eq::net::DataOStream::operator<< (const std::vector< int32_t > & value) [inline]
Optimized specialization to write a std::vector of int32_t.
Definition at line 277 of file dataOStream.h.
template<> DataOStream& eq::net::DataOStream::operator<< (const std::vector< int64_t > & value) [inline]
Optimized specialization to write a std::vector of int64_t.
Definition at line 287 of file dataOStream.h.
template<typename T > DataOStream& eq::net::DataOStream::operator<< (const T & value) [inline]
Write a plain data item by copying it to the stream.
Definition at line 83 of file dataOStream.h.
References write().
template<> DataOStream& eq::net::DataOStream::operator<< (const std::vector< ObjectVersion > & value) [inline]
Optimized specialization to write a std::vector of ObjectVersion.
Definition at line 302 of file dataOStream.h.
template<> DataOStream& eq::net::DataOStream::operator<< (const std::vector< float > & value) [inline]
Optimized specialization to write a std::vector of float.
Definition at line 292 of file dataOStream.h.
template<typename T > DataOStream& eq::net::DataOStream::operator<< (const std::vector< T > & value)
Write a std::vector of serializable items.
template<> DataOStream& eq::net::DataOStream::operator<< (const std::vector< uint8_t > & value) [inline]
Optimized specialization to write a std::vector of uint8_t.
Definition at line 267 of file dataOStream.h.
template<> DataOStream& eq::net::DataOStream::operator<< (const std::vector< double > & value) [inline]
Optimized specialization to write a std::vector of double.
Definition at line 297 of file dataOStream.h.
template<> DataOStream& eq::net::DataOStream::operator<< (const std::vector< uint64_t > & value) [inline]
Optimized specialization to write a std::vector of uint64_t.
Definition at line 282 of file dataOStream.h.
void eq::net::DataOStream::resend (NodePtr node, const bool useMulticast)
Resend the saved buffer to the given node.
void eq::net::DataOStream::resend (const Nodes & receivers)
Resend the saved buffer to all given nodes.
virtual void eq::net::DataOStream::reset () [protected, virtual]
Reset the whole stream.
virtual void eq::net::DataOStream::sendData (const uint32_t compressor, const uint32_t nChunks, const void *const * chunks, const uint64_t * chunkSizes, const uint64_t size) [protected, pure virtual]
Send a data buffer (packet) to the receivers.
template<typename C > void eq::net::DataOStream::serializeChildren (const std::vector< C * > & children)
Serialize child objects.
The DataIStream has a deserialize counterpart to this method. All child objects have to be registered or mapped beforehand.
void eq::net::DataOStream::write (const void * data, uint64_t size)
Write a number of bytes from data into the stream.
Referenced by operator<<().
The documentation for this class was generated from the following file:
dataOStream.h