Collage: co::base::Buffer< T > Class Template Reference
co::base::Buffer< T > Class Template Reference
A simple memory buffer with some helper functions.
#include <buffer.h>
Public Member Functions
Buffer ()
Construct a new, empty buffer.
Buffer (const uint64_t size)
Construct a new buffer of the given size.
~Buffer ()
Destruct the buffer.
void clear ()
Flush the buffer, deleting all data.
T * pack ()
Tighten the allocated memory to the size of the buffer.
Buffer (Buffer &from)
Copy constructor, transfers ownership to new Buffer.
const Buffer & operator= (Buffer &from)
Assignment operator, copies data from Buffer.
T & operator[] (const uint64_t position)
Direct access to the element at the given index.
const T & operator[] (const uint64_t position) const
Direct const access to an element.
T * resize (const uint64_t newSize)
Ensure that the buffer contains at least newSize elements.
void grow (const uint64_t newSize)
Ensure that the buffer contains at least newSize elements.
T * reserve (const uint64_t newSize)
Ensure that the buffer contains at least newSize elements.
T * reset (const uint64_t newSize)
Set the buffer size and malloc enough memory.
void append (const T *data, const uint64_t size)
Append elements to the buffer, increasing the size.
void append (const T &element)
Append one element to the buffer.
void replace (const void *data, const uint64_t size)
Replace the existing data with new data.
void swap (Buffer &buffer)
Swap the buffer contents with another Buffer.
T * getData ()
const T * getData () const
bool setSize (const uint64_t size)
Set the size of the buffer without changing its allocation.
uint64_t getSize () const
bool isEmpty () const
uint64_t getMaxSize () const
Detailed Description
template<typename T>
class co::base::Buffer< T >
A simple memory buffer with some helper functions.
For bigger data (>100k) using a std::vector< uint8_t > has a high overhead when resizing (>1ms). This buffer just memcpy's elements, i.e., it should only be used for PODs since the copy constructor or assignment operator is not called on the copied elements. Primarily used for binary data, e.g., in eq::Image. The implementation works like a pool, that is, data is only released when the buffer is deleted or clear() is called.
Definition at line 38 of file buffer.h.
Constructor & Destructor Documentation
template<typename T> co::base::Buffer< T >::Buffer () [inline]
Construct a new, empty buffer.
Version:
1.0
Definition at line 42 of file buffer.h.
template<typename T> co::base::Buffer< T >::Buffer (const uint64_t size) [inline]
Construct a new buffer of the given size.
Version:
1.0
Definition at line 45 of file buffer.h.
template<typename T> co::base::Buffer< T >::~Buffer () [inline]
Destruct the buffer.
Version:
1.0
Definition at line 49 of file buffer.h.
template<typename T> co::base::Buffer< T >::Buffer (Buffer< T > & from) [inline]
Copy constructor, transfers ownership to new Buffer.
Version:
1.0
Definition at line 72 of file buffer.h.
Member Function Documentation
template<typename T> void co::base::Buffer< T >::append (const T * data, const uint64_t size) [inline]
Append elements to the buffer, increasing the size.
Version:
1.0
Definition at line 161 of file buffer.h.
template<typename T> void co::base::Buffer< T >::append (const T & element) [inline]
Append one element to the buffer.
Version:
1.0
Definition at line 172 of file buffer.h.
template<typename T> void co::base::Buffer< T >::clear () [inline]
Flush the buffer, deleting all data.
Version:
1.0
Definition at line 52 of file buffer.h.
Referenced by co::base::Buffer< pollfd >::~Buffer().
template<typename T> T* co::base::Buffer< T >::getData () [inline]
Returns:
a pointer to the data.
Version:
1.0
Definition at line 206 of file buffer.h.
template<typename T> const T* co::base::Buffer< T >::getData () const [inline]
Returns:
a const pointer to the data.
Version:
1.0
Definition at line 209 of file buffer.h.
template<typename T> uint64_t co::base::Buffer< T >::getMaxSize () const [inline]
Returns:
the maximum size of the buffer.
Version:
1.0
Definition at line 236 of file buffer.h.
template<typename T> uint64_t co::base::Buffer< T >::getSize () const [inline]
Returns:
the current size.
Version:
1.0
Definition at line 230 of file buffer.h.
template<typename T> void co::base::Buffer< T >::grow (const uint64_t newSize) [inline]
Ensure that the buffer contains at least newSize elements.
Existing data is retained. The size is increased, if necessary.
Version:
1.0
Definition at line 120 of file buffer.h.
template<typename T> bool co::base::Buffer< T >::isEmpty () const [inline]
Returns:
true if the buffer is empty, false if not.
Version:
1.0
Definition at line 233 of file buffer.h.
template<typename T> const Buffer& co::base::Buffer< T >::operator= (Buffer< T > & from) [inline]
Assignment operator, copies data from Buffer.
Version:
1.0
Definition at line 79 of file buffer.h.
template<typename T> const T& co::base::Buffer< T >::operator[] (const uint64_t position) const [inline]
Direct const access to an element.
Version:
1.0
Definition at line 90 of file buffer.h.
template<typename T> T& co::base::Buffer< T >::operator[] (const uint64_t position) [inline]
Direct access to the element at the given index.
Version:
1.0
Definition at line 86 of file buffer.h.
template<typename T> T* co::base::Buffer< T >::pack () [inline]
Tighten the allocated memory to the size of the buffer.
Returns:
the new pointer to the first element.
Version:
1.0
Definition at line 60 of file buffer.h.
template<typename T> void co::base::Buffer< T >::replace (const void * data, const uint64_t size) [inline]
Replace the existing data with new data.
Version:
1.0
Definition at line 179 of file buffer.h.
Referenced by co::base::Buffer< pollfd >::operator=().
template<typename T> T* co::base::Buffer< T >::reserve (const uint64_t newSize) [inline]
Ensure that the buffer contains at least newSize elements.
Existing data may be deleted.
Returns:
the new pointer to the first element.
Version:
1.0
Definition at line 133 of file buffer.h.
Referenced by co::base::Buffer< pollfd >::replace(), and co::base::Buffer< pollfd >::reset().
template<typename T> T* co::base::Buffer< T >::reset (const uint64_t newSize) [inline]
Set the buffer size and malloc enough memory.
Existing data may be deleted.
Returns:
the new pointer to the first element.
Version:
1.0
Definition at line 153 of file buffer.h.
Referenced by co::base::Buffer< pollfd >::Buffer().
template<typename T> T* co::base::Buffer< T >::resize (const uint64_t newSize) [inline]
Ensure that the buffer contains at least newSize elements.
Existing data is retained. The size is set.
Returns:
the new pointer to the first element.
Version:
1.0
Definition at line 100 of file buffer.h.
Referenced by co::base::Buffer< pollfd >::append(), and co::base::Buffer< pollfd >::grow().
template<typename T> bool co::base::Buffer< T >::setSize (const uint64_t size) [inline]
Set the size of the buffer without changing its allocation.
This method only modifies the size parameter. If the current allocation of the buffer is too small, it asserts, returns false and does not change the size.
Version:
1.0
Definition at line 219 of file buffer.h.
Referenced by co::base::Buffer< pollfd >::reset().
template<typename T> void co::base::Buffer< T >::swap (Buffer< T > & buffer) [inline]
Swap the buffer contents with another Buffer.
Version:
1.0
Definition at line 190 of file buffer.h.
The documentation for this class was generated from the following file:
buffer.h