Collage: eq::net::Object Class Reference
eq::net::Object Class Reference
A generic, distributed object.
#include <object.h>
Public Member Functions
Object ()
Construct a new distributed object.
virtual ~Object ()
Destruct the distributed object.
Data Access
bool isAttached () const
LocalNodePtr getLocalNode ()
const base::UUID & getID () const
uint32_t getInstanceID () const
bool isMaster () const
Versioning
virtual ChangeType getChangeType () const
virtual bool isDirty () const
Return if this object needs a commit.
uint128_t commit ()
Commit a new version of this object.
virtual uint32_t commitNB ()
Start committing a new version of this object.
virtual uint128_t commitSync (const uint32_t commitID)
Finalize a commit transaction.
void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
uint32_t getAutoObsolete () const
uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
uint128_t getHeadVersion () const
uint128_t getVersion () const
uint128_t getOldestVersion () const
virtual void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
Serialization methods for instantiation and versioning.
virtual void getInstanceData (DataOStream &os)=0
Serialize all instance information of this distributed object.
virtual void applyInstanceData (DataIStream &is)=0
Deserialize the instance data.
virtual void pack (DataOStream &os)
Serialize the modifications since the last call to commit().
virtual void unpack (DataIStream &is)
Deserialize a change.
Packet Transmission
bool send (NodePtr node, ObjectPacket &packet)
Send a packet to peer object instance(s) on another node.
bool send (NodePtr node, ObjectPacket &packet, const std::string &string)
Send a packet to peer object instance(s) on another node.
bool send (NodePtr node, ObjectPacket &packet, const void *data, const uint64_t size)
Send a packet to peer object instance(s) on another node.
Notifications
virtual void notifyAttached ()
Notify that this object has been registered or mapped.
virtual void notifyDetach ()
Notify that this object will be deregistered or unmapped.
void setID (const base::UUID &identifier)
uint32_t getMasterInstanceID () const
const NodeID & getMasterNodeID () const
uint128_t addSlave (Command &command)
void removeSlave (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual void attach (const base::UUID &id, const uint32_t instanceID)
virtual void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Types
enum ChangeType {
NONE, STATIC, INSTANCE, DELTA,
UNBUFFERED
}
Object change handling characteristics, see Programming Guide.
Protected Member Functions
Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Friends
class DeltaMasterCM
class FullMasterCM
class MasterCM
class StaticMasterCM
class StaticSlaveCM
class UnbufferedMasterCM
class VersionedSlaveCM
Detailed Description
A generic, distributed object.
Please refer to the Programming Guide and examples on how to develop and use distributed objects.
See also:
eq::Object
Definition at line 39 of file object.h.
Member Enumeration Documentation
enum eq::net::Object::ChangeType
Object change handling characteristics, see Programming Guide.
Enumerator:
STATIC
non-versioned, static object.
INSTANCE
use only instance data
DELTA
use pack/unpack delta
UNBUFFERED
versioned, but don't retain versions
Definition at line 43 of file object.h.
Constructor & Destructor Documentation
eq::net::Object::Object ()
Construct a new distributed object.
virtual eq::net::Object::~Object () [virtual]
Destruct the distributed object.
eq::net::Object::Object (const Object &) [protected]
Copy constructor.
Member Function Documentation
virtual void eq::net::Object::applyInstanceData (DataIStream & is) [pure virtual]
Deserialize the instance data.
This method is called during object mapping to populate slave instances with the master object's data.
Parameters:
is the input stream.
Implemented in eq::net::Barrier.
Referenced by unpack().
uint128_t eq::net::Object::commit ()
Commit a new version of this object.
This method is a convenience function for commitSync(commitNB()).
Objects using the change type STATIC can not be committed.
Master instances will increment new versions continously, starting at VERSION_FIRST. If the object has not changed, no new version will be generated, that is, the current version is returned. The high value of the returned version will always be 0.
Slave objects can be commited, but have certain caveats for serialization. Please refer to the Programming Guide for more details. Slave object commits will return a random version on a successful commit, or VERSION_NONE if the object has not changed since the last commit. The high value of a successful commit will never be 0.
Returns:
the new head version.
See also:
commitNB(), commitSync()
virtual uint32_t eq::net::Object::commitNB () [virtual]
Start committing a new version of this object.
The commit transaction has to be completed using commitSync, passing the returned identifier.
Returns:
the commit identifier to be passed to commitSync
See also:
commitSync()
virtual uint128_t eq::net::Object::commitSync (const uint32_t commitID) [virtual]
Finalize a commit transaction.
Parameters:
commitID the commit identifier returned from commitNB
Returns:
the new head version.
See also:
commit()
uint32_t eq::net::Object::getAutoObsolete () const
Returns:
get the number of versions this object retains.
virtual ChangeType eq::net::Object::getChangeType () const [inline, virtual]
Returns:
how the changes are to be handled.
Reimplemented in eq::net::Barrier.
Definition at line 84 of file object.h.
References STATIC.
uint128_t eq::net::Object::getHeadVersion () const
Returns:
the latest available (head) version.
const base::UUID& eq::net::Object::getID () const [inline]
Returns:
the object's unique identifier.
Definition at line 70 of file object.h.
Referenced by eq::net::DataIStream::operator>>().
virtual void eq::net::Object::getInstanceData (DataOStream & os) [pure virtual]
Serialize all instance information of this distributed object.
Parameters:
os The output stream.
Implemented in eq::net::Barrier.
Referenced by pack().
uint32_t eq::net::Object::getInstanceID () const [inline]
Returns:
the node-wide unique object instance identifier.
Definition at line 73 of file object.h.
LocalNodePtr eq::net::Object::getLocalNode () [inline]
Returns:
the local node to which this object is mapped, or 0 if the object is not mapped.
Definition at line 67 of file object.h.
uint128_t eq::net::Object::getOldestVersion () const
Returns:
the oldest available version.
uint128_t eq::net::Object::getVersion () const
Returns:
the currently synchronized version.
bool eq::net::Object::isAttached () const [inline]
Returns:
true if the object is attached, mapped or registered.
Definition at line 61 of file object.h.
Referenced by eq::net::DataOStream::operator<<().
virtual bool eq::net::Object::isDirty () const [inline, virtual]
Return if this object needs a commit.
This function is used for optimization, to detect early that no commit is needed. If it returns true, pack() or getInstanceData() will be executed. The serialization methods can still decide to not write any data, upon which no new version will be created. If it returns false, commitNB() and commitSync() will exit early.
Returns:
true if a commit is needed.
Definition at line 97 of file object.h.
bool eq::net::Object::isMaster () const
Returns:
true if this instance is the master version, false otherwise.
virtual void eq::net::Object::notifyAttached () [inline, virtual]
Notify that this object has been registered or mapped.
The method is called from the thread initiating the registration or mapping, after the operation has been completed successfully.
See also:
isMaster()
Definition at line 279 of file object.h.
virtual void eq::net::Object::notifyDetach () [virtual]
Notify that this object will be deregistered or unmapped.
The method is called from the thread initiating the deregistration or unmapping, before the operation is executed.
See also:
isMaster()
virtual void eq::net::Object::notifyNewHeadVersion (const uint128_t & version) [virtual]
Notification that a new head version was received by a slave object.
The notification is send from the command thread, which is different from the node main thread. The object should not be sync()'ed from this notification, as this might lead to synchronization issues with the application thread changing the object. Its purpose is to send a message to the application, which then takes the appropriate action.
Parameters:
version The new head version.
virtual void eq::net::Object::notifyNewVersion () [inline, virtual]
Notification that a new version was received by a master object.
See also:
comment in notifyNewHeadVersion().
Definition at line 217 of file object.h.
const Object& eq::net::Object::operator= (const Object &) [inline, protected]
NOP assignment operator.
Definition at line 347 of file object.h.
virtual void eq::net::Object::pack (DataOStream & os) [inline, virtual]
Serialize the modifications since the last call to commit().
No new version will be created if no data is written to the output stream.
Parameters:
os the output stream.
Reimplemented in eq::net::Barrier.
Definition at line 247 of file object.h.
References getInstanceData().
bool eq::net::Object::send (NodePtr node, ObjectPacket & packet)
Send a packet to peer object instance(s) on another node.
bool eq::net::Object::send (NodePtr node, ObjectPacket & packet, const std::string & string)
Send a packet to peer object instance(s) on another node.
bool eq::net::Object::send (NodePtr node, ObjectPacket & packet, const void * data, const uint64_t size)
Send a packet to peer object instance(s) on another node.
void eq::net::Object::setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
The versions for the last count commits are retained. The actual number of versions retained may be less since a commit does not always generate a new version.
Parameters:
count the number of versions to retain, excluding the head version.
uint128_t eq::net::Object::sync (const uint128_t & version = VERSION_HEAD)
Sync to a given version.
Objects using the change type STATIC can not be synced.
Syncing to VERSION_HEAD syncs up to the last received version, does not block and always returns true. Syncing to VERSION_NEXT applies one new version, potentially blocking. Syncing to VERSION_NONE does nothing.
Slave objects can be synced to VERSION_HEAD, VERSION_NEXT or to any version generated by a commit on the master instance. Syncing to a concrete version applies all pending deltas up to this version and potentially blocks.
Master objects can only be synced to VERSION_HEAD, VERSION_NEXT or to any version generated by a commit on a slave instance. Syncing to a concrete version applies only this version and potentially blocks.
The different sync semantics for concrete versions originate from the fact that master versions are continous and ordered, while slave versions are random and unordered.
This function is not thread safe, that is, calling sync() simultaneously from multiple threads has to be protected by the caller using a mutex.
Parameters:
version the version to synchronize (see above).
Returns:
the last version applied.
virtual void eq::net::Object::unpack (DataIStream & is) [inline, virtual]
Deserialize a change.
Parameters:
is the input data stream.
Reimplemented in eq::net::Barrier.
Definition at line 254 of file object.h.
References applyInstanceData().
The documentation for this class was generated from the following file:
object.h