Collage: co::CommandQueue Class Reference
co::CommandQueue Class Reference
A CommandQueue is a thread-safe queue for command packets.
#include <commandQueue.h>
Public Member Functions
virtual CO_API void push (Command &packet)
Push a command to the queue.
virtual CO_API void pushFront (Command &packet)
Push a command to the front of the queue.
virtual void wakeup ()
Wake up the command queue, pop() will return 0.
virtual CO_API Command * pop (const uint32_t timeout=EQ_TIMEOUT_INDEFINITE)
Pop a command from the queue.
virtual CO_API Command * tryPop ()
Try to pop a command from the queue.
bool isEmpty () const
CO_API void flush ()
Flush all cached commands.
size_t getSize () const
EQ_TS_VAR (_thread)
Detailed Description
A CommandQueue is a thread-safe queue for command packets.
Definition at line 34 of file commandQueue.h.
Member Function Documentation
CO_API void co::CommandQueue::flush ()
Flush all cached commands.
size_t co::CommandQueue::getSize () const [inline]
Returns:
the size of the queue.
Definition at line 84 of file commandQueue.h.
References co::base::MTQueue< T, S >::getSize().
bool co::CommandQueue::isEmpty () const [inline]
Returns:
true if the command queue is empty, false if not.
Definition at line 78 of file commandQueue.h.
References co::base::MTQueue< T, S >::isEmpty().
virtual CO_API Command* co::CommandQueue::pop (const uint32_t timeout = EQ_TIMEOUT_INDEFINITE) [virtual]
Pop a command from the queue.
The returned command has to be released after usage.
Parameters:
timeout the time in ms to wait for the operation.
Returns:
the next command in the queue.
Exceptions:
Exception on timeout.
virtual CO_API void co::CommandQueue::push (Command & packet) [virtual]
Push a command to the queue.
Parameters:
packet the command packet.
virtual CO_API void co::CommandQueue::pushFront (Command & packet) [virtual]
Push a command to the front of the queue.
virtual CO_API Command* co::CommandQueue::tryPop () [virtual]
Try to pop a command from the queue.
The returned command has to be released after usage.
Returns:
the next command in the queue, or 0 if no command is queued.
virtual void co::CommandQueue::wakeup () [inline, virtual]
Wake up the command queue, pop() will return 0.
Definition at line 51 of file commandQueue.h.
References co::base::MTQueue< T, S >::push().
The documentation for this class was generated from the following file:
commandQueue.h