Collage: eq::net::LocalNode Class Reference
eq::net::LocalNode Class Reference
Specialization of a local node.
#include <localNode.h>
Classes
class CommandThread
The command handler thread.
class ReceiverThread
The receiver thread.
Public Member Functions
void ackRequest (NodePtr node, const uint32_t requestID)
void expireInstanceData (const int64_t age)
State Changes
The following methods affect the state of the node by changing its connectivity to the network.
virtual bool initLocal (const int argc, char **argv)
Initialize the node.
virtual bool listen ()
Open all connections and put this node into the listening state.
virtual bool close ()
Close a listening node.
virtual bool exitLocal ()
Close a listening node.
bool connect (NodePtr node)
Connect a proxy node to this listening node.
NodePtr connect (const NodeID &nodeID)
Create and connect a node given by an identifier.
virtual bool disconnect (NodePtr node)
Disconnects a connected node.
Object Registry
void disableInstanceCache ()
Disable the instance cache of an stopped local node.
bool registerObject (Object *object)
Register a distributed object.
virtual void deregisterObject (Object *object)
Deregister a distributed object.
bool mapObject (Object *object, const base::UUID &id, const uint128_t &version=VERSION_OLDEST)
Map a distributed object.
bool mapObject (Object *object, const ObjectVersion &v)
Convenience wrapper for mapObject().
uint32_t mapObjectNB (Object *object, const base::UUID &id, const uint128_t &version=VERSION_OLDEST)
Start mapping a distributed object.
bool mapObjectSync (const uint32_t requestID)
Finalize the mapping of a distributed object.
void unmapObject (Object *object)
Unmap a mapped object.
void releaseObject (Object *object)
Convenience method to deregister or unmap an object.
void swapObject (Object *oldObject, Object *newObject)
Data Access
NodePtr getNode (const NodeID &id) const
Get a node by identifier.
void getNodes (Nodes &nodes) const
Assemble a vector of the currently connected nodes.
void acquireSendToken (NodePtr toNode)
void releaseSendToken (NodePtr toNode)
virtual CommandQueue * getCommandThreadQueue ()
Return the command queue to the command thread.
bool inCommandThread () const
Operations
void addListener (ConnectionPtr connection)
Add a listening connection to this listening node.
uint32_t removeListenerNB (ConnectionPtr connection)
Remove a listening connection from this listening node.
void flushCommands ()
Flush all pending commands on this listening node.
Command & cloneCommand (Command &command)
bool dispatchCommand (Command &command)
Dispatches a packet to the registered command queue.
Protected Member Functions
bool _connect (NodePtr node, ConnectionPtr connection)
Connect a node proxy to this node.
Friends
class ObjectStore
Detailed Description
Specialization of a local node.
Local nodes listen on network connections, manage connections to other nodes and provide session registration, mapping and command dispatch.
Definition at line 53 of file localNode.h.
Member Function Documentation
bool eq::net::LocalNode::_connect (NodePtr node, ConnectionPtr connection) [protected]
Connect a node proxy to this node.
This node has to be in the listening state. The node proxy will be put in the connected state upon success. The connection has to be connected.
Parameters:
node the remote node.
connection the connection to the remote node.
Returns:
true if the node was connected correctly, false otherwise.
void eq::net::LocalNode::addListener (ConnectionPtr connection)
Add a listening connection to this listening node.
virtual bool eq::net::LocalNode::close () [virtual]
Close a listening node.
Disconnects all connected node proxies, closes the listening connections and terminates all threads created in listen().
Returns:
true if the node was stopped, false if it was not stopped.
Referenced by exitLocal().
bool eq::net::LocalNode::connect (NodePtr node)
Connect a proxy node to this listening node.
The connection descriptions of the node are used to connect the node. On success, the node is in the connected state, otherwise its state is unchanged.
This method is one-sided, that is, the node to be connected should not initiate a connection to this node at the same time.
Parameters:
node the remote node.
Returns:
true if this node was connected, false otherwise.
See also:
initConnect, syncConnect
NodePtr eq::net::LocalNode::connect (const NodeID & nodeID)
Create and connect a node given by an identifier.
This method is two-sided and thread-safe, that is, it can be called by mulltiple threads on the same node with the same nodeID, or concurrently on two nodes with each others' nodeID.
Parameters:
nodeID the identifier of the node to connect.
Returns:
the connected node, or an invalid RefPtr if the node could not be connected.
virtual void eq::net::LocalNode::deregisterObject (Object * object) [virtual]
Deregister a distributed object.
Parameters:
object the object instance.
void eq::net::LocalNode::disableInstanceCache ()
Disable the instance cache of an stopped local node.
virtual bool eq::net::LocalNode::disconnect (NodePtr node) [virtual]
Disconnects a connected node.
Parameters:
node the remote node.
Returns:
true if the node was disconnected correctly, false otherwise.
bool eq::net::LocalNode::dispatchCommand (Command & command) [virtual]
Dispatches a packet to the registered command queue.
Parameters:
command the command.
Returns:
the result of the operation.
See also:
Command::invoke
Reimplemented from eq::net::Dispatcher.
void eq::net::LocalNode::flushCommands () [inline]
Flush all pending commands on this listening node.
This causes the receiver thread to redispatch all pending commands, which are normally only redispatched when a new command is received.
Definition at line 282 of file localNode.h.
References eq::net::ConnectionSet::interrupt().
virtual CommandQueue* eq::net::LocalNode::getCommandThreadQueue () [inline, virtual]
Return the command queue to the command thread.
Definition at line 258 of file localNode.h.
NodePtr eq::net::LocalNode::getNode (const NodeID & id) const
Get a node by identifier.
The node might not be connected.
Parameters:
id the node identifier.
Returns:
the node.
void eq::net::LocalNode::getNodes (Nodes & nodes) const
Assemble a vector of the currently connected nodes.
bool eq::net::LocalNode::inCommandThread () const [inline]
Returns:
true if executed from the command handler thread, false if not.
Definition at line 265 of file localNode.h.
virtual bool eq::net::LocalNode::initLocal (const int argc, char ** argv) [virtual]
Initialize the node.
Before calling listen(), the '--eq-listen <connection description>' command line options is recognized by this method to add listening connections to this node. This parameter might be used multiple times. ConnectionDescription::fromString() is used to parse the provided description.
Please note that further command line parameters are recognized by eq::init().
Parameters:
argc the command line argument count.
argv the command line argument values.
Returns:
true if the client was successfully initialized, false otherwise.
virtual bool eq::net::LocalNode::listen () [virtual]
Open all connections and put this node into the listening state.
The node will spawn a receiver and command thread, and listen on all connections for incoming commands. The node will be in the listening state if the method completed successfully. A listening node can connect other nodes.
Returns:
true if the node could be initialized, false if not.
See also:
connect
bool eq::net::LocalNode::mapObject (Object * object, const ObjectVersion & v) [inline]
Convenience wrapper for mapObject().
Definition at line 215 of file localNode.h.
References mapObject().
Referenced by mapObject().
bool eq::net::LocalNode::mapObject (Object * object, const base::UUID & id, const uint128_t & version = VERSION_OLDEST)
Map a distributed object.
The mapped object becomes a slave instance of the master version which was registered with the provided identifier. The given version can be used to map a specific version.
If VERSION_NONE is provided, the slave instance is not initialized with any data from the master. This is useful if the object has been pre-initialized by other means, for example from a shared file system.
If VERSION_OLDEST is provided, the oldest available version is mapped.
If the requested version does no longer exist, mapObject() will fail. If the requested version is newer than the head version, mapObject() will block until the requested version is available.
Mapping an object is a potentially time-consuming operation. Using mapObjectNB() and mapObjectSync() to asynchronously map multiple objects in parallel improves performance of this operation.
Parameters:
object the object.
id the master object identifier.
version the initial version.
Returns:
true if the object was mapped, false if the master of the object is not found or the requested version is no longer available.
See also:
registerObject
uint32_t eq::net::LocalNode::mapObjectNB (Object * object, const base::UUID & id, const uint128_t & version = VERSION_OLDEST)
Start mapping a distributed object.
bool eq::net::LocalNode::mapObjectSync (const uint32_t requestID)
Finalize the mapping of a distributed object.
bool eq::net::LocalNode::registerObject (Object * object)
Register a distributed object.
Registering a distributed object makes this object the master version. The object's identifier is used to map slave instances of the object. Master versions of objects are typically writable and can commit new versions of the distributed object.
Parameters:
object the object instance.
Returns:
true if the object was registered, false otherwise.
void eq::net::LocalNode::releaseObject (Object * object)
Convenience method to deregister or unmap an object.
uint32_t eq::net::LocalNode::removeListenerNB (ConnectionPtr connection)
Remove a listening connection from this listening node.
void eq::net::LocalNode::unmapObject (Object * object)
Unmap a mapped object.
Parameters:
object the mapped object.
The documentation for this class was generated from the following file:
localNode.h