Collage: eq::base::Condition Class Reference
eq::base::Condition Class Reference
A condition variable and associated lock.
#include <condition.h>
Public Member Functions
Condition ()
Construct a new condition variable.
~Condition ()
Destruct this condition variable.
void lock ()
Lock the mutex.
void signal ()
Signal the condition.
void broadcast ()
Broadcast the condition.
void unlock ()
Unlock the mutex.
void wait ()
Atomically unlock the mutex, wait for a signal and relock the mutex.
Detailed Description
A condition variable and associated lock.
Follows closely pthread_condition and mutex
Definition at line 34 of file condition.h.
Constructor & Destructor Documentation
eq::base::Condition::Condition ()
Construct a new condition variable.
Version:
1.0
eq::base::Condition::~Condition ()
Destruct this condition variable.
Version:
1.0
Member Function Documentation
void eq::base::Condition::broadcast ()
Broadcast the condition.
Version:
1.0
Referenced by eq::base::Monitor< State >::operator++(), eq::base::Monitor< State >::operator--(), eq::base::Monitor< State >::operator|=(), and eq::base::Monitor< State >::set().
void eq::base::Condition::lock ()
Lock the mutex.
Version:
1.0
Referenced by eq::base::MTQueue< Command * >::clear(), eq::base::MTQueue< Command * >::getBack(), eq::base::MTQueue< Command * >::getFront(), eq::base::Monitor< State >::operator++(), eq::base::Monitor< State >::operator--(), eq::base::MTQueue< Command * >::operator=(), eq::base::Monitor< State >::operator|=(), eq::base::MTQueue< Command * >::pop(), eq::base::MTQueue< Command * >::push(), eq::base::MTQueue< Command * >::pushFront(), eq::base::Monitor< State >::set(), eq::base::MTQueue< Command * >::tryPop(), eq::base::Monitor< State >::waitEQ(), eq::base::Monitor< State >::waitGE(), eq::base::Monitor< State >::waitLE(), and eq::base::Monitor< State >::waitNE().
void eq::base::Condition::signal ()
Signal the condition.
Version:
1.0
Referenced by eq::base::MTQueue< Command * >::operator=(), eq::base::MTQueue< Command * >::push(), and eq::base::MTQueue< Command * >::pushFront().
void eq::base::Condition::unlock ()
Unlock the mutex.
Version:
1.0
Referenced by eq::base::MTQueue< Command * >::clear(), eq::base::MTQueue< Command * >::getBack(), eq::base::MTQueue< Command * >::getFront(), eq::base::Monitor< State >::operator++(), eq::base::Monitor< State >::operator--(), eq::base::MTQueue< Command * >::operator=(), eq::base::Monitor< State >::operator|=(), eq::base::MTQueue< Command * >::pop(), eq::base::MTQueue< Command * >::push(), eq::base::MTQueue< Command * >::pushFront(), eq::base::Monitor< State >::set(), eq::base::MTQueue< Command * >::tryPop(), eq::base::Monitor< State >::waitEQ(), eq::base::Monitor< State >::waitGE(), eq::base::Monitor< State >::waitLE(), and eq::base::Monitor< State >::waitNE().
void eq::base::Condition::wait ()
Atomically unlock the mutex, wait for a signal and relock the mutex.
Version:
1.0
Referenced by eq::base::MTQueue< Command * >::pop(), eq::base::Monitor< State >::waitEQ(), eq::base::Monitor< State >::waitGE(), eq::base::Monitor< State >::waitLE(), and eq::base::Monitor< State >::waitNE().
The documentation for this class was generated from the following file:
condition.h