Collage: co::base::Condition Class Reference
co::base::Condition Class Reference
A condition variable and associated lock.
#include <condition.h>
Public Member Functions
COBASE_API Condition ()
Construct a new condition variable.
COBASE_API ~Condition ()
Destruct this condition variable.
COBASE_API void lock ()
Lock the mutex.
COBASE_API void unlock ()
Unlock the mutex.
COBASE_API void signal ()
Signal the condition.
COBASE_API void broadcast ()
Broadcast the condition.
COBASE_API void wait ()
Atomically unlock the mutex, wait for a signal and relock the mutex.
COBASE_API bool timedWait (const uint32_t timeout)
Atomically unlock the mutex, wait for a signal and relock the mutex.
Detailed Description
A condition variable and associated lock.
Follows closely pthread_condition and mutex
Definition at line 35 of file condition.h.
Constructor & Destructor Documentation
COBASE_API co::base::Condition::Condition ()
Construct a new condition variable.
Version:
1.0
COBASE_API co::base::Condition::~Condition ()
Destruct this condition variable.
Version:
1.0
Member Function Documentation
COBASE_API void co::base::Condition::broadcast ()
Broadcast the condition.
Version:
1.0
Referenced by co::base::Monitor< State >::operator++(), co::base::Monitor< State >::operator--(), co::base::Monitor< State >::operator|=(), and co::base::Monitor< State >::set().
COBASE_API void co::base::Condition::lock ()
Lock the mutex.
Version:
1.0
Referenced by co::base::MTQueue< Command * >::clear(), co::base::MTQueue< Command * >::getBack(), co::base::MTQueue< Command * >::getFront(), co::base::Monitor< State >::operator++(), co::base::Monitor< State >::operator--(), co::base::MTQueue< Command * >::operator=(), co::base::Monitor< State >::operator|=(), co::base::MTQueue< Command * >::pop(), co::base::MTQueue< Command * >::push(), co::base::MTQueue< Command * >::pushFront(), co::base::Monitor< State >::set(), co::base::MTQueue< Command * >::timedPop(), co::base::Monitor< State >::timedWaitEQ(), co::base::Monitor< State >::timedWaitGE(), co::base::MTQueue< Command * >::tryPop(), co::base::Monitor< State >::waitEQ(), co::base::Monitor< State >::waitGE(), co::base::Monitor< State >::waitLE(), co::base::Monitor< State >::waitNE(), and co::base::MTQueue< Command * >::waitSize().
COBASE_API void co::base::Condition::signal ()
Signal the condition.
Version:
1.0
Referenced by co::base::MTQueue< Command * >::operator=(), co::base::MTQueue< Command * >::pop(), co::base::MTQueue< Command * >::push(), co::base::MTQueue< Command * >::pushFront(), co::base::MTQueue< Command * >::timedPop(), and co::base::MTQueue< Command * >::tryPop().
COBASE_API bool co::base::Condition::timedWait (const uint32_t timeout)
Atomically unlock the mutex, wait for a signal and relock the mutex.
The operation is aborted after the given timeout and false is returned.
Parameters:
timeout the timeout in milliseconds to wait for the signal.
Returns:
true on success, false on timeout.
Version:
1.0
Referenced by co::base::MTQueue< Command * >::timedPop(), co::base::Monitor< State >::timedWaitEQ(), and co::base::Monitor< State >::timedWaitGE().
COBASE_API void co::base::Condition::unlock ()
Unlock the mutex.
Version:
1.0
Referenced by co::base::MTQueue< Command * >::clear(), co::base::MTQueue< Command * >::getBack(), co::base::MTQueue< Command * >::getFront(), co::base::Monitor< State >::operator++(), co::base::Monitor< State >::operator--(), co::base::MTQueue< Command * >::operator=(), co::base::Monitor< State >::operator|=(), co::base::MTQueue< Command * >::pop(), co::base::MTQueue< Command * >::push(), co::base::MTQueue< Command * >::pushFront(), co::base::Monitor< State >::set(), co::base::MTQueue< Command * >::timedPop(), co::base::Monitor< State >::timedWaitEQ(), co::base::Monitor< State >::timedWaitGE(), co::base::MTQueue< Command * >::tryPop(), co::base::Monitor< State >::waitEQ(), co::base::Monitor< State >::waitGE(), co::base::Monitor< State >::waitLE(), co::base::Monitor< State >::waitNE(), and co::base::MTQueue< Command * >::waitSize().
COBASE_API void co::base::Condition::wait ()
Atomically unlock the mutex, wait for a signal and relock the mutex.
Version:
1.0
Referenced by co::base::MTQueue< Command * >::pop(), co::base::MTQueue< Command * >::push(), co::base::MTQueue< Command * >::pushFront(), co::base::Monitor< State >::waitEQ(), co::base::Monitor< State >::waitGE(), co::base::Monitor< State >::waitLE(), co::base::Monitor< State >::waitNE(), and co::base::MTQueue< Command * >::waitSize().
The documentation for this class was generated from the following file:
condition.h