Collage: eq::base::uint128_t Class Reference
eq::base::uint128_t Class Reference
A base type for 128 bit unsigned integer values.
#include <uint128_t.h>
Public Member Functions
uint128_t (const uint64_t low_=0)
Construct a new 128 bit integer with a default value.
uint128_t (const uint64_t high_, const uint64_t low_)
Construct a new 128 bit integer with default values.
uint128_t & operator= (const uint128_t &rhs)
Assign another 128 bit value.
bool operator== (const uint128_t &rhs) const
bool operator!= (const uint128_t &rhs) const
bool operator< (const uint128_t &rhs) const
bool operator> (const uint128_t &rhs) const
bool operator<= (const uint128_t &rhs) const
bool operator>= (const uint128_t &rhs) const
uint128_t & operator++ ()
Increment the value.
uint128_t & operator-- ()
Decrement the value.
const uint64_t & low () const
const uint64_t & high () const
uint64_t & low ()
uint64_t & high ()
std::string getShortString () const
Detailed Description
A base type for 128 bit unsigned integer values.
Definition at line 39 of file uint128_t.h.
Constructor & Destructor Documentation
eq::base::uint128_t::uint128_t (const uint64_t low_ = 0) [inline]
Construct a new 128 bit integer with a default value.
Version:
1.0
Definition at line 46 of file uint128_t.h.
eq::base::uint128_t::uint128_t (const uint64_t high_, const uint64_t low_) [inline]
Construct a new 128 bit integer with default values.
Version:
1.0
Definition at line 53 of file uint128_t.h.
Member Function Documentation
std::string eq::base::uint128_t::getShortString () const [inline]
Returns:
a short, but not necessarily unique, string of the value.
Definition at line 162 of file uint128_t.h.
const uint64_t& eq::base::uint128_t::high () const [inline]
Returns:
the reference to the high 64 bits of this 128 bit value.
Definition at line 154 of file uint128_t.h.
Referenced by eq::base::UUID::isGenerated(), eq::base::operator+(), eq::base::operator-(), eq::base::UUID::operator=(), and eq::base::UUID::UUID().
uint64_t& eq::base::uint128_t::high () [inline]
Returns:
the reference to the high 64 bits of this 128 bit value.
Definition at line 159 of file uint128_t.h.
const uint64_t& eq::base::uint128_t::low () const [inline]
Returns:
the reference to the lower 64 bits of this 128 bit value.
Definition at line 152 of file uint128_t.h.
Referenced by eq::base::operator+(), eq::base::operator-(), eq::base::UUID::operator=(), and eq::base::UUID::UUID().
uint64_t& eq::base::uint128_t::low () [inline]
Returns:
the reference to the lower 64 bits of this 128 bit value.
Definition at line 157 of file uint128_t.h.
bool eq::base::uint128_t::operator!= (const uint128_t & rhs) const [inline]
Returns:
true if the values are different, false otherwise.
Version:
1.0
Definition at line 75 of file uint128_t.h.
uint128_t& eq::base::uint128_t::operator++ (void) [inline]
Increment the value.
Version:
1.0
Definition at line 133 of file uint128_t.h.
uint128_t& eq::base::uint128_t::operator-- (void) [inline]
Decrement the value.
Version:
1.0
Definition at line 143 of file uint128_t.h.
bool eq::base::uint128_t::operator< (const uint128_t & rhs) const [inline]
Returns:
true if this value is smaller than the RHS value.
Version:
1.0
Definition at line 82 of file uint128_t.h.
bool eq::base::uint128_t::operator<= (const uint128_t & rhs) const [inline]
Returns:
true if this value is smaller or equal than the RHS value.
Version:
1.0
Definition at line 109 of file uint128_t.h.
uint128_t& eq::base::uint128_t::operator= (const uint128_t & rhs) [inline]
Assign another 128 bit value.
Version:
1.0
Definition at line 57 of file uint128_t.h.
bool eq::base::uint128_t::operator== (const uint128_t & rhs) const [inline]
Returns:
true if the values are equal, false if not.
Version:
1.0
Definition at line 68 of file uint128_t.h.
bool eq::base::uint128_t::operator> (const uint128_t & rhs) const [inline]
Returns:
true if this value is bigger than the rhs value.
Version:
1.0
Definition at line 95 of file uint128_t.h.
bool eq::base::uint128_t::operator>= (const uint128_t & rhs) const [inline]
Returns:
true if this value is smaller or equal than the RHS value.
Version:
1.0
Definition at line 123 of file uint128_t.h.
The documentation for this class was generated from the following file:
uint128_t.h