Collage: co::base::uint128_t Class Reference
co::base::uint128_t Class Reference
A base type for 128 bit unsigned integer values.
#include <uint128_t.h>
Public Member Functions
uint128_t (const uint64_t low_=0)
Construct a new 128 bit integer with a default value.
uint128_t (const uint64_t high_, const uint64_t low_)
Construct a new 128 bit integer with default values.
uint128_t & operator= (const uint128_t &rhs)
Assign another 128 bit value.
uint128_t & operator= (const uint64_t rhs)
Assign another 64 bit value.
COBASE_API uint128_t & operator= (const std::string &from)
Assign an 128 bit value from a std::string.
bool operator== (const uint128_t &rhs) const
bool operator!= (const uint128_t &rhs) const
bool operator< (const uint128_t &rhs) const
bool operator> (const uint128_t &rhs) const
bool operator<= (const uint128_t &rhs) const
bool operator>= (const uint128_t &rhs) const
uint128_t & operator++ ()
Increment the value.
uint128_t & operator-- ()
Decrement the value.
const uint64_t & low () const
const uint64_t & high () const
uint64_t & low ()
uint64_t & high ()
std::string getShortString () const
Static Public Attributes
static COBASE_API const uint128_t ZERO
The NULL value.
Detailed Description
A base type for 128 bit unsigned integer values.
Definition at line 39 of file uint128_t.h.
Constructor & Destructor Documentation
co::base::uint128_t::uint128_t (const uint64_t low_ = 0) [inline]
Construct a new 128 bit integer with a default value.
Version:
1.0
Definition at line 46 of file uint128_t.h.
co::base::uint128_t::uint128_t (const uint64_t high_, const uint64_t low_) [inline, explicit]
Construct a new 128 bit integer with default values.
Version:
1.0
Definition at line 53 of file uint128_t.h.
Member Function Documentation
std::string co::base::uint128_t::getShortString () const [inline]
Returns:
a short, but not necessarily unique, string of the value.
Definition at line 173 of file uint128_t.h.
const uint64_t& co::base::uint128_t::high () const [inline]
Returns:
the reference to the high 64 bits of this 128 bit value.
Definition at line 165 of file uint128_t.h.
Referenced by co::base::UUID::isGenerated(), co::base::operator&(), co::base::operator+(), co::base::operator-(), co::base::operator|(), and co::base::UUID::UUID().
uint64_t& co::base::uint128_t::high () [inline]
Returns:
the reference to the high 64 bits of this 128 bit value.
Definition at line 170 of file uint128_t.h.
const uint64_t& co::base::uint128_t::low () const [inline]
Returns:
the reference to the lower 64 bits of this 128 bit value.
Definition at line 163 of file uint128_t.h.
Referenced by co::base::operator&(), co::base::operator+(), co::base::operator-(), co::base::operator|(), and co::base::UUID::UUID().
uint64_t& co::base::uint128_t::low () [inline]
Returns:
the reference to the lower 64 bits of this 128 bit value.
Definition at line 168 of file uint128_t.h.
bool co::base::uint128_t::operator!= (const uint128_t & rhs) const [inline]
Returns:
true if the values are different, false otherwise.
Version:
1.0
Definition at line 86 of file uint128_t.h.
uint128_t& co::base::uint128_t::operator++ (void) [inline]
Increment the value.
Version:
1.0
Definition at line 144 of file uint128_t.h.
uint128_t& co::base::uint128_t::operator-- (void) [inline]
Decrement the value.
Version:
1.0
Definition at line 154 of file uint128_t.h.
bool co::base::uint128_t::operator< (const uint128_t & rhs) const [inline]
Returns:
true if this value is smaller than the RHS value.
Version:
1.0
Definition at line 93 of file uint128_t.h.
bool co::base::uint128_t::operator<= (const uint128_t & rhs) const [inline]
Returns:
true if this value is smaller or equal than the RHS value.
Version:
1.0
Definition at line 120 of file uint128_t.h.
uint128_t& co::base::uint128_t::operator= (const uint128_t & rhs) [inline]
Assign another 128 bit value.
Version:
1.0
Definition at line 57 of file uint128_t.h.
uint128_t& co::base::uint128_t::operator= (const uint64_t rhs) [inline]
Assign another 64 bit value.
Version:
1.1.1
Definition at line 65 of file uint128_t.h.
COBASE_API uint128_t& co::base::uint128_t::operator= (const std::string & from)
Assign an 128 bit value from a std::string.
Version:
1.0
Reimplemented in co::base::UUID.
bool co::base::uint128_t::operator== (const uint128_t & rhs) const [inline]
Returns:
true if the values are equal, false if not.
Version:
1.0
Definition at line 79 of file uint128_t.h.
bool co::base::uint128_t::operator> (const uint128_t & rhs) const [inline]
Returns:
true if this value is bigger than the rhs value.
Version:
1.0
Definition at line 106 of file uint128_t.h.
bool co::base::uint128_t::operator>= (const uint128_t & rhs) const [inline]
Returns:
true if this value is smaller or equal than the RHS value.
Version:
1.0
Definition at line 134 of file uint128_t.h.
Member Data Documentation
COBASE_API const uint128_t co::base::uint128_t::ZERO [static]
The NULL value.
Version:
1.1.1
Definition at line 183 of file uint128_t.h.
The documentation for this class was generated from the following file:
uint128_t.h